# Generated by Django 5.2.3 on 2025-07-05 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[
                    ("movies", "Movies"),
                    ("physics", "Physics"),
                    ("chemistry", "Chemistry"),
                    ("geography", "Geography"),
                    ("history", "History"),
                    ("sports", "Sports"),
                ],
                default="movies",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 5, 10, 11, 12, 216692, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
